### ISSUE TITLE
反馈青春杯两个BUG

### ISSUE THREAD

**Issue by SyakesanHso** [MinamiChiwa/Trainers-Legend-G#108]
不知道是不是只有我一个人遇到这两个BUG...（贴图替换已关闭但是还是会遇到）
紫爆魂训练后游戏会卡住，如图
![QQ截图20230122150613](https://user-images.githubusercontent.com/104615557/213904775-8118e0d2-9b66-49f3-b806-96ab1e140ea6.png)
![QQ截图20230122150623](https://user-images.githubusercontent.com/104615557/213904780-d56d59ea-a06e-4202-b87f-2de34bff3cf3.png)
↑重开游戏可以解决

青春杯的最后一次比赛，点击本番后会卡住，如图
![QQ截图20230122154713](https://user-images.githubusercontent.com/104615557/213905808-adccbc65-a001-473d-a0b7-ec325cb14d3d.png)
![QQ截图20230122154719](https://user-images.githubusercontent.com/104615557/213905809-08692fbb-41ac-42c9-9fb7-713ddb1c3d5b.png)
 
盲猜应该是贴图卡了，求救呜呜呜谢谢大佬们

**Comment by SyakesanHso** [comment]
最新版本

**Comment by ChihyuenWang** [comment]
我个人在本机测试，未能复现问题1。从问题2的截图上看，你似乎已将本插件的核心功能停用。在这种情况下，也会出现问题吗？
![bf58c09f9cf2f2bc42cc3f6dd9093410](https://user-images.githubusercontent.com/12523783/214079659-0a27a628-ddae-4203-ab63-07acbf8634a7.png)

**Comment by SyakesanHso** [comment]
> 

谢谢回复和测试。应该是我这台老人机电脑的问题，我想重下赛马娘试试

**Comment by SyakesanHso** [comment]
> 我个人在本机测试，未能复现问题1。从问题2的截图上看，你似乎已将本插件的核心功能停用。在这种情况下，也会出现问题吗？ ![bf58c09f9cf2f2bc42cc3f6dd9093410](https://user-images.githubusercontent.com/12523783/214079659-0a27a628-ddae-4203-ab63-07acbf8634a7.png)

我在电脑重新下载DMM端的赛马娘数据文件，现在已经解决了，谢谢了。

**Comment by ChihyuenWang** [comment]
今后若在使用本插件时遇到其他问题，欢迎继续与我们沟通。
