### ISSUE TITLE
关于HTTP服务器端口配置

### ISSUE THREAD

**Issue by capric98** [MinamiChiwa/Trainers-Legend-G#111]
目前 `httpServerPort` 选项仅能填写端口数值，而开启该功能后默认listen到 `*:{httpServerPort}`，是否能增加一个配置选项使其默认绑定到localhost上？或者使这里支持填写类似 `127.0.0.1:43214` 的地址

**Comment by chinosk6** [comment]
目前没有相关配置。是绑定到0.0.0.0有什么不便吗

**Comment by capric98** [comment]
> 目前没有相关配置。是绑定到0.0.0.0有什么不便吗

有一些安全上的担心……机器有公网IP，虽然防火墙会block掉http请求……

**Comment by chinosk6** [comment]
有公网那确实要注意一下，虽然这个服务没啥用(
之后会改成默认 127.0.0.1 的

**Comment by capric98** [comment]
> 有公网那确实要注意一下，虽然这个服务没啥用( 之后会改成默认 127.0.0.1 的

非常感谢！

**Comment by ChihyuenWang** [comment]
最新发行版 [v0.92.0](https://github.com/MinamiChiwa/Trainers-Legend-G/releases/tag/v0.92.0) 已将 HTTP Server 绑定地址从 0.0.0.0 修改为 127.0.0.1。
