### ISSUE TITLE
关于version.dll不能同时支持Legend g和透视插件

### ISSUE THREAD

**Issue by Miukind** [MinamiChiwa/Trainers-Legend-G#112]
有没有某个版本的version.dll可以同时兼容两个插件，或者有没有可以解决此问题的办法呢？

**Comment by ChihyuenWang** [comment]
最新发行版 [v0.92.0](https://github.com/MinamiChiwa/Trainers-Legend-G/releases/tag/v0.92.0) 支持自行加载其它 DLL 插件。请自行研究其使用方法。
