### ISSUE TITLE
进入育成时崩溃

### ISSUE THREAD

**Issue by shiramineS** [MinamiChiwa/Trainers-Legend-G#114]
![capture_20230226102522742](https://user-images.githubusercontent.com/127011696/222948489-44d5315f-b23d-4368-a202-334871f39ba7.jpg)
![capture_20230305153050312](https://user-images.githubusercontent.com/127011696/222948500-8532fac1-7726-4389-b152-b2fa157993a4.jpg)
[legend_g_plugin_log.log](https://github.com/MinamiChiwa/Trainers-Legend-G/files/10891312/legend_g_plugin_log.log)
[Player.log](https://github.com/MinamiChiwa/Trainers-Legend-G/files/10891313/Player.log)
[Player-prev.log](https://github.com/MinamiChiwa/Trainers-Legend-G/files/10891314/Player-prev.log)

**Comment by chinosk6** [comment]
能提供一下复现此问题的步骤吗?

**Comment by shiramineS** [comment]
> 能提供一下复现此问题的步骤吗?

大师杯速子新马级12月后半，开的快进没看到是哪个事件就炸了，现在点继续育成加载中就崩也看不了
配卡速北黑sr东商力神鹰米浴智大和高峰

**Comment by ChihyuenWang** [comment]
最新发行版 [v0.92.0](https://github.com/MinamiChiwa/Trainers-Legend-G/releases/tag/v0.92.0) 对「故事文本发生异常时，输入错误日志而不闪退」这一特性再度进行了修正。请更新后再次查看。[ERROR]报错会带有问题事件的ID，烦请上报给我们。
![6cecdd0c0c0b24ab09ff9ac0b19899e1](https://user-images.githubusercontent.com/12523783/223137234-5a6593cd-846a-448f-89a2-fc539e819212.png)

**Comment by ChihyuenWang** [comment]
若有其他问题请再行反馈。本 issue 关闭。
