### ISSUE TITLE
目白莱恩育成事件游戏崩溃

### ISSUE THREAD

**Issue by Ukyuko** [MinamiChiwa/Trainers-Legend-G#115]
目白莱恩育成事件
肌肉……有什么不可能！？（筋肉に不可能は......）
不管是育成遇到还是图鉴里点进去都会崩溃，育成中遇到了只能关游戏把version暂时移走，过了事件再重新放回去，要不然连育成都点不开
![QQ截图20230306035816](https://user-images.githubusercontent.com/127052487/222982949-39446349-536d-48ce-b41f-544d0f9a394a.png)

**Comment by ChihyuenWang** [comment]
最新发行版 [v0.92.0](https://github.com/MinamiChiwa/Trainers-Legend-G/releases/tag/v0.92.0) 对「故事文本发生异常时，输入错误日志而不闪退」这一特性再度进行了修正。请更新后再次查看。
![6cecdd0c0c0b24ab09ff9ac0b19899e1](https://user-images.githubusercontent.com/12523783/223137234-5a6593cd-846a-448f-89a2-fc539e819212.png)

**Comment by ChihyuenWang** [comment]
若有其他问题请再行反馈。本 issue 关闭。
