### ISSUE TITLE
部分角色个人剧情在使用全局角色替换后出现「错误 返回标题」的问题

### ISSUE THREAD

**Issue by AgnesDigitalIO** [MinamiChiwa/Trainers-Legend-G#117]
在使用全局角色替换后，部分角色个人剧情出现返回标题的弹窗，请修复一下，谢谢
![Uploading 屏幕截图 2023-03-08 172047.png…]()

**Comment by chinosk6** [comment]
请提供复现过程，并正确上传截图

**Comment by chinosk6** [comment]
能**提供复现过程**吗

**Comment by AgnesDigitalIO** [comment]
可以提供一下，以下是复现过程
在故事-赛马娘故事-点击大拓太阳神的个人剧情第7话，使用了全局角色替换，就会出现错误 返回标题
![屏幕截图 2023-03-09 070245](https://user-images.githubusercontent.com/122211469/223873082-0495735f-5ff5-4280-a3c0-e99d75795289.png)
此时控制台没有发现

**Comment by AgnesDigitalIO** [comment]
系统是Windows 11 build 25309（Canary）

**Comment by chinosk6** [comment]
#131 已尝试修复此问题，可以在 [Action](https://github.com/MinamiChiwa/Trainers-Legend-G/actions/runs/4779922307) 下载测试。
