### ISSUE TITLE
更新 v0.92.1 后自定义字体不可用

### ISSUE THREAD

**Issue by zyf722** [MinamiChiwa/Trainers-Legend-G#122]
在更新最新版本的 dll 后，先前自行重新打包的 .assetbundle 文件中的自定义字体失效。

请问在更新支持加载多个自定义 AssetBundle 的 feature 后，需要重新打包 .assetbundle 吗？

**Comment by chinosk6** [comment]
不用重新打包。保证配置里面的文件名大小写和assetbundle里面的大小写一致即可。

**Comment by zyf722** [comment]
> 不用重新打包。保证配置里面的文件名大小写和assetbundle里面的大小写一致即可。

刚刚测试发现是大小写问题，感谢回答！
