### ISSUE TITLE
Live亮度異常與部分呈現異常

### ISSUE THREAD

**Issue by yotv2000tw** [MinamiChiwa/Trainers-Legend-G#125]
## 版本與配置
- 插件：[繁體中文 `Ver.0.05.0` -> `Ver.0.05.1`（大致對應簡體中文 `v0.92.2` -> `v0.92.3`）](https://github.com/yotv2000tw/Trainers-Legend-G-TRANS-zh-tw/releases/tag/Ver.0.05.1)
- 遊戲：`1.28.6`
- 均無開啟自由視角

## 問題圖片
![ver0 05 1-issue-2](https://user-images.githubusercontent.com/51760140/228764956-87139b96-cf77-4e1a-8350-5d8f9f129672.png)

![68dd9016ff9819e5749b2b35f0e00b43](https://user-images.githubusercontent.com/51760140/228756131-1456f1e9-be7b-4c78-86b1-05115fc52481.png)

![image](https://user-images.githubusercontent.com/51760140/228760962-07a72e01-13e2-42a2-afba-cd50377799e0.png)

## 概述
1. Live亮度異常（FOV不確定是否也有問題，但至少正常觀賞是會，主頁亮度貌似沒有影響）
2. 遠景異常（主要觀察到的是嘴巴跟部分臉型在遠景上會變得很奇怪，自由視角FOV模式則貌似不會有這個問題）
   1. 遠景的嘴型貌似變成張口。
   2. 遠景的臉型出現扭曲。
   3. 近景的嘴巴也有部分呈現異常（尚待確認是否是這個版本開始發生的問題）。

**Comment by chinosk6** [comment]
已于 [871aed7](https://github.com/MinamiChiwa/Trainers-Legend-G/pull/123/commits/871aed7132211e47cfa6c67e46d7b6489de75687) 修复此问题
