### ISSUE TITLE
关于是否支持向指定URL发送数据包

### ISSUE THREAD

**Issue by SakiAllStar** [MinamiChiwa/Trainers-Legend-G#128]
由于相关解包软件原理为通过截取相关数据包实现透视功能，一般通过ura-core(推荐)或EXNOA-CarrotJuice来完成，想问下Trainers-Legend-G是否也支持类似的功能呢？

**Comment by chinosk6** [comment]
TLG 主要是本地化插件，不内置任何可能破坏游戏公平的功能。

**Comment by chinosk6** [comment]
如果你需要同时使用 TLG 和其它插件，可以使用 TLG 的 `加载其它DLL插件` 的功能。在 `配置设置` 页面可以找到此选项。
