### ISSUE TITLE
[快速登录] 网络问题

### ISSUE THREAD

**Issue by Weidows** [MinamiChiwa/Trainers-Legend-G#130]
通过快速登录-使用缓存登录进入游戏时, 发现`api-umamusume.cygames.jp` 这个域名没被加速器截到, 走的clash代理(偶尔能进入游戏但是肯定特别慢), 关了clash后这个域名是直连就一直连接失败

通过DMM进入游戏就没有这个问题, 试了多个加速器(应该不是加速器本身的问题)

**Comment by chinosk6** [comment]
加速器本身只会加速从DMM打开的游戏，快速登录启动的游戏自然不会被加速。如果你是使用UU、ACGP之类的加速器，肯定是没办法直接用快速登录的。

**Comment by Weidows** [comment]
解决了

之前快速登录-登录一直报错, 换节点和加速器都没好
```
 Error: LocationParseError('Failed to parse: http://127.0.0.1:7890
```

重置了下网络+重启, 之后重新进行快速登录就好了

最上面提到的域名没走加速器代理问题可能是之前的网络缓存 存在错误, 刷新下凭证就好了
