### ISSUE TITLE
请问有考虑过将汉化补丁移植到安卓上面吗

### ISSUE THREAD

**Issue by Specialweek2023** [MinamiChiwa/Trainers-Legend-G#133]

**Comment by chinosk6** [comment]
https://github.com/akemimadoka/UmaPyogin-Android

**Comment by Specialweek2023** [comment]
好，谢谢，请问这个该怎么安装？

**Comment by chinosk6** [comment]
Xposed 插件，已 root 推荐用 [LSPosed](https://github.com/LSPosed/LSPosed)，没 root 用 [LSPatch](https://github.com/LSPosed/LSPatch)
