### ISSUE TITLE
增加设置启动时的窗口位置

### ISSUE THREAD

**Issue by Chaojiu** [MinamiChiwa/Trainers-Legend-G#136]
外部插件中，配置设置 里的 设置启动时的分辨率（resolution_start）只能设置分辨率数值，而 More→窗口设置 中的 更改窗口位置/大小 可以设置窗口坐标。
目前我的窗口设置是 x 640 , y -15 , w 576 , h 1024 
每次进游戏要手动点比较麻烦，能否在启动时自动设置？

**Comment by chinosk6** [comment]
已在 v0.94.0 中添加了此功能。
添加一个名为 `OnLoad` 的参数即可
