### ISSUE TITLE
译文文本小错误

### ISSUE THREAD

**Issue by Chaojiu** [MinamiChiwa/Trainers-Legend-G#137]
![image](https://github.com/MinamiChiwa/Trainers-Legend-G/assets/31241183/118f3e7a-192b-4b13-9a4a-3b0eca66da64)
文本重复，位置是 赛马娘故事 樱花进王 第6话

**Comment by ChihyuenWang** [comment]
修正已完成，将在插件下次译文更新中体现。感谢支持。

**Comment by Chaojiu** [comment]
![image](https://github.com/MinamiChiwa/Trainers-Legend-G/assets/31241183/f8fc5bf4-e373-459f-a476-d02815f8fffe)
应该是打错字了，上→伤害
位置是 主线剧情 第4章 第5话

**Comment by ChihyuenWang** [comment]
> ![image](https://user-images.githubusercontent.com/31241183/259585267-f8fc5bf4-e373-459f-a476-d02815f8fffe.png) 应该是打错字了，上→伤害 位置是 主线剧情 第4章 第5话

此处已修正，将在插件下次译文更新中体现。感谢支持，今后有发现译文笔误问题还请继续提出。
