### ISSUE TITLE
游戏为非活动窗口时可触发CutIn第一人称快捷键

### ISSUE THREAD

**Issue by Chaojiu** [MinamiChiwa/Trainers-Legend-G#142]
本来还以为是什么玄学BUG，容易出现在游戏挂后台的时候，看到更新内容翻了项目Wiki才发现是触发了新功能。
F键还是挺常用的，玩的时候开个浏览器输点东西就可能误触发。
能否修改为组合按键或者监测游戏的窗口状态为活动窗口时再检测按键触发？或者加个勾勾选择是否启用该功能？

**Comment by chinosk6** [comment]
下个版本添加

**Comment by ChihyuenWang** [comment]
发行版 [v0.94.1](https://github.com/MinamiChiwa/Trainers-Legend-G/releases/tag/v0.94.1) 已发布。本版本中新增了 CutIn 场景第一人称开关（默认关闭）。感谢支持！
