### ISSUE TITLE
微软运行库安装完还是内存报错

### ISSUE THREAD

**Issue by Joker0224** [MinamiChiwa/Trainers-Legend-G#148]
- 
[Player.log](https://github.com/MinamiChiwa/Trainers-Legend-G/files/12266221/Player.log)

**Comment by Joker0224** [comment]
![G_D)%2_@{~$HHYAB(ZSE11](https://github.com/MinamiChiwa/Trainers-Legend-G/assets/141474687/6aae42b6-9208-4132-b0ef-d9faa711b602)

**Comment by Joker0224** [comment]
下载的0.942直接解压到游戏目录 然后 dmm启动游戏报错

**Comment by chinosk6** [comment]
https://github.com/abbodi1406/vcredist
