### ISSUE TITLE
更新新版本后启动赛马娘崩溃

### ISSUE THREAD

**Issue by ScottLiu1** [MinamiChiwa/Trainers-Legend-G#149]
![微信图片_20230813153718](https://github.com/MinamiChiwa/Trainers-Legend-G/assets/142141585/9df05519-9444-4235-9d30-22fdb8c6230c)

**Comment by ScottLiu1** [comment]
运行库也安装了。。还是不行 不装的话就能进去

**Comment by ScottLiu1** [comment]
[Player.log](https://github.com/MinamiChiwa/Trainers-Legend-G/files/12329027/Player.log)

**Comment by ChihyuenWang** [comment]
本机测试，最新版本客户端搭配最新版本插件完全正常。请提供更为精确的插件版本信息。请尝试[安装此运行库](https://github.com/abbodi1406/vcredist/releases)。

![Snipaste_2023-08-13_16-02-15](https://github.com/MinamiChiwa/Trainers-Legend-G/assets/12523783/dc0da893-cefa-4eee-94db-5dbafc26a149)

**Comment by ScottLiu1** [comment]
> 本机测试，最新版本客户端搭配最新版本插件完全正常。请提供更为精确的插件版本信息。请尝试[安装此运行库](https://github.com/abbodi1406/vcredist/releases)。
> 
> ![Snipaste_2023-08-13_16-02-15](https://user-images.githubusercontent.com/12523783/260289716-dc0da893-cefa-4eee-94db-5dbafc26a149.png)

插件版本v0.94.2 应该是最新的 游戏我打不开 一打开游戏进程都打不开就弹出内存不足 之前是能用的 今天突然就打不开了

**Comment by ScottLiu1** [comment]
> 本机测试，最新版本客户端搭配最新版本插件完全正常。请提供更为精确的插件版本信息。请尝试[安装此运行库](https://github.com/abbodi1406/vcredist/releases)。
> 
> ![Snipaste_2023-08-13_16-02-15](https://user-images.githubusercontent.com/12523783/260289716-dc0da893-cefa-4eee-94db-5dbafc26a149.png)

![image](https://github.com/MinamiChiwa/Trainers-Legend-G/assets/142141585/922f4ada-989a-41b7-8db2-cc317e92908e)
w我删了插件打开是这样的

**Comment by ScottLiu1** [comment]
运行库我也安装完了 装的64位的，我电脑就是64位

**Comment by ScottLiu1** [comment]
并且发现了个很神奇的事 我甚至删掉全部插件 只装基础的FPS解锁补丁 可以进游戏 但是解锁补丁一点效果都没有 就很奇怪

**Comment by ChihyuenWang** [comment]
根据阁下反映的情况，暂无法定位到插件侧存在任何问题
