### ISSUE TITLE
更新 v0.94.3 后默认字体发生变化

### ISSUE THREAD

**Issue by Chaojiu** [MinamiChiwa/Trainers-Legend-G#151]
更新后发现字体有变化，手动删除下回 v0.94.2 后恢复到了之前的状态。
我看插件里字体路径还是原来的，文件也还是msyh.ttc，不应产生变化才对。并且现在字体像是日文字体，所以认为是bug。
图片在下面
<details>

**↓最新版本 v0.94.3**
![最新](https://github.com/MinamiChiwa/Trainers-Legend-G/assets/31241183/f97da7f0-ab3a-4945-a8c8-35f8a5674601)

**↓上一个版本 v0.94.2**
 ![0 94 2](https://github.com/MinamiChiwa/Trainers-Legend-G/assets/31241183/31fce630-948b-4dae-95d5-728b878e4390)

**↓ 关闭插件中的替换字体功能 v0.94.3 （94.2看起来也一样）**
 ![关闭替换字体](https://github.com/MinamiChiwa/Trainers-Legend-G/assets/31241183/0c82dcb0-6cec-4669-9e01-a4a98a84bda7)

**Comment by ChihyuenWang** [comment]
未定位到发行版本体存在问题。请按[此页面](https://github.com/MinamiChiwa/Trainers-Legend-G/wiki/%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE) 检查字体配置（另请注意“msyh.ttc”应是全小写而非大写）。

**Comment by Chaojiu** [comment]
我用AssetStudio查看了umamusumelocalify文件，发现 v0.94.3 里面包含的字体是msyh.ttf而非msyh.ttc，
v0.94.2里的字体是ttc。
修改新版插件字体地址为ttf后恢复正常。

**Comment by ChihyuenWang** [comment]
我复查了一下，确实如你所说。这个应该是我打包时的疏忽。
稍后会将仓库 Wiki 等各处写的默认设置也进行修改。今后的发行版更新，也会格外留意后缀名之类的细节问题。
感谢反馈。
