### ISSUE TITLE
勾选自由视角比赛马娘会消失

### ISSUE THREAD

**Issue by CCJINTINGJUN** [MinamiChiwa/Trainers-Legend-G#161]
到了结算又有显示了

**Comment by ThunderFox1897** [comment]
同样问题 开启自由视角马娘立刻全部消失 关闭自由视角又全都出现了

**Comment by CCJINTINGJUN** [comment]
![QQ截图20231108121357](https://github.com/MinamiChiwa/Trainers-Legend-G/assets/150129267/b3126f87-8dcc-4706-95d3-975387373514)
原来不是消失了 是错位了  这怎么解

**Comment by ThunderFox1897** [comment]
> ![QQ截图20231108121357](https://user-images.githubusercontent.com/150129267/281258625-b3126f87-8dcc-4706-95d3-975387373514.png) 原来不是消失了 是错位了 这怎么解

我发现马娘人没了的时候乱调视角会看得到一个一堆多边形抽搐的画面，我就知道是模型错位并且挤在一起了，只是我一直没找到她们在哪，原来在水池里233

**Comment by AgnesDigitalIO** [comment]
> 了

我看umaview的issue称，赛马娘使用了一个新模型渲染方式：通用渲染管线，应该是这个导致的

**Comment by ChihyuenWang** [comment]
[v0.94.8](https://github.com/MinamiChiwa/Trainers-Legend-G/releases/tag/v0.94.8)已发布，[修正了该问题](https://github.com/MinamiChiwa/Trainers-Legend-G/pull/158/commits/87f9b1efddf962016854acb31a274b6dd62f734f)。
