### ISSUE TITLE
部分角色剧情使用全局替换后有概率会出现卡加载的问题

### ISSUE THREAD

**Issue by AgnesDigitalIO** [MinamiChiwa/Trainers-Legend-G#162]
问题发生的全过程：使用全局角色替换后打开大拓太阳神剧情第7话的时候有概率会出现卡加载的情况（不知道cy又改啥了，看umaview称，赛马娘改模型渲染方式了）
以下是问题截图：![image](https://github.com/MinamiChiwa/Trainers-Legend-G/assets/122211469/b1f24e69-cb6f-44f8-a83f-5f585f5e5cbd)（图片是插件使用id102426的画面
             ![image](https://github.com/MinamiChiwa/Trainers-Legend-G/assets/122211469/613ffb07-78a0-4fcb-a6d6-f132a8c8437b)（此图片是出现卡加载的问题）

**Comment by ChihyuenWang** [comment]
[v0.94.8](https://github.com/MinamiChiwa/Trainers-Legend-G/releases/tag/v0.94.8)已发布，[修正了该问题](https://github.com/MinamiChiwa/Trainers-Legend-G/pull/158/commits/87f9b1efddf962016854acb31a274b6dd62f734f)。
