### ISSUE TITLE
無法更新

### ISSUE THREAD

**Issue by zhao-ng327** [MinamiChiwa/Trainers-Legend-G#181]
第一次安裝，是下載目前最新的版本，但是會彈窗顯示需要更新，且更新內容是約一年前的文本(如圖)，進遊戲也確實有文本未翻譯，而新出的內容如創昇的漢字反而是有翻譯到的。有試過直接替換譯文倉庫的內容進localized_data以及重新安裝馬娘，皆無效果
![image](https://github.com/MinamiChiwa/Trainers-Legend-G/assets/61046297/aaff5c46-c2fd-4cdc-85f3-b919a8269eb2)
![image](https://github.com/MinamiChiwa/Trainers-Legend-G/assets/61046297/3fb66906-2678-42f3-9640-0d81b615e6ce)
![image](https://github.com/MinamiChiwa/Trainers-Legend-G/assets/61046297/5767ca00-79fd-4bc8-a6f3-8a03fdd4106a)

**Comment by ChihyuenWang** [comment]
繁中区用户请使用[繁体中文发行版](https://github.com/yotv2000tw/Trainers-Legend-G-TRANS-zh-tw)，或参照该仓库的 README 文件手动更改翻译文档更新 API
