### ISSUE TITLE
2024年5月28日起插件失效问题

### ISSUE THREAD

**Issue by ChihyuenWang** [MinamiChiwa/Trainers-Legend-G#189]
在 2024 年 5 月 28 日的游戏客户端更新中，Cygames 以空前力度「封杀」了所有 DLL 注入类第三方工具。本插件是日起无法正常运作。
作为实质上违反游戏使用条款的外部工具，项目贡献者将审慎应对本次事态。**我们并不保证该项目将来会持续更新。**
发送有关该问题的 issue，将不获回复、直接被关闭。

**Comment by yingyingyingqwq** [comment]
SAD
😭

**Comment by ChihyuenWang** [comment]
[v0.98.0](https://github.com/MinamiChiwa/Trainers-Legend-G/releases/tag/v0.98.0) 现已推出，暂时性恢复了插件的正常运作。但是，如果游戏管理方进一步采取措施，不保证本插件未来能够持续、稳定地进行维护与更新。
