### ISSUE TITLE
无法更改更多设置

### ISSUE THREAD

**Issue by zhuaajian** [MinamiChiwa/Trainers-Legend-G#192]
![image](https://github.com/MinamiChiwa/Trainers-Legend-G/assets/42296194/f99b5ca2-7586-4a73-9882-6852bf400a20)

0.98版本，打开游戏后会自动弹出这个提示，然后点开更多设置，点保存也会出现，无法修改更多设置里的选项。

**Comment by chinosk6** [comment]
删除 `epconf.json` 文件即可
