### ISSUE TITLE
无法连接到URA：ConnectionTimeout

### ISSUE THREAD

**Issue by AZXM2021** [MinamiChiwa/Trainers-Legend-G#198]
启动时会出现一个报错框，点忽略也能正常使用，只是每次启动都会弹出来。我看控制台是运行“GameAssembly.dll”就弹出报错
![1](https://github.com/user-attachments/assets/2b8f11ec-6444-4a8b-ba5e-103ecaaeb3d5)

**Comment by chinosk6** [comment]
非本项目内容
