### ISSUE TITLE
无法启动游戏

### ISSUE THREAD

**Issue by CTDE42** [MinamiChiwa/Trainers-Legend-G#199]
老家回来更新插件游戏之后无法启动游戏，起初以为是游戏的问题便重新安装，安装之后自启动成功，但插件安装之后无法启动我便意识到插件问题，更改version.dll文件名关闭插件后启动成功，且插件正常随附启动汉化正常

**Comment by ChihyuenWang** [comment]
本次客户端更新后，将会检测 version.dll ，有则无法启动。发布新版本时，默认了大部分用户已清空游戏根目录（则 version.dll 已被删除），没有单独进行说明。今后发布发行版时将尽可能多作详细说明。
