### ISSUE TITLE
Set Trans Failed

### ISSUE THREAD

**Issue by Shiba-ru** [MinamiChiwa/Trainers-Legend-G#204]
Im getting this error everytime time the game fails to boot 

![image](https://github.com/user-attachments/assets/738fcf1b-b2de-4c6d-bdeb-296429e82f6c)

**Comment by ChihyuenWang** [comment]
Please use the latest release [v0.102.0](https://github.com/MinamiChiwa/Trainers-Legend-G/releases/tag/v0.102.0)
