### ISSUE TITLE
ERROR 24/12/23～

### ISSUE THREAD

**Issue by SuKeni2024** [MinamiChiwa/Trainers-Legend-G#208]
After updating Uma Musume in DMMPlayer today, I can no longer use it again.
<img width="1104" alt="2406ed3a457d942b423dc68f0a778fe4" src="https://github.com/user-attachments/assets/af602a6f-c7fb-41ca-9eda-ca3e68c1ef55" />

**Comment by ChihyuenWang** [comment]
fixed
