### ISSUE TITLE
To ask many questions

### ISSUE THREAD

**Issue by pengg999** [MinamiChiwa/Trainers-Legend-G#43]
Hi guys, thanks for your great development
I really appreciate for your works
I'm korean umamusume gamer and want to translate it into korean
Can you guys make some little guideline for me?
I'm so novice for programming so little bit hard for me
Can you guys help me?

**Comment by ChihyuenWang** [comment]
Dear @pengg999 ,
First of all, thank you for your recognition of Trainers-Legend-G project.
No offense, but as far as we know, Kakao Games is about to introduce the Korean version of Umamusume to your country. Are you sure you still wanna do the localization work? XD
If you have any questions about the localization, plz explain them more specifically and clearly, and the rest contributors can try to answer them for you.

**Comment by pengg999** [comment]
ahh yes thank you very much
yes most of players want to keep playing in Japan server ( Global server )
And maybe we can meet and race somedays in global server
So I need to play in global server right? haha

First of all, what's the point of static.json in localized_data?
I think it doesn't matter for translation status, I delete it and test it several times
but I don't know why it is in file

Second, as you know chinese language can show long meaning with short words
but not for korean and japanese. I think you guys change something for sentence change
so long sentence keep spread out of screen not change into next line
So can you tell me how to fix it?

Finally, I don't know what exactly config.json do for each command
I make it blank for auto-update github path ( because I can't use your great updated work sadly)
but don't know why there is command about static and hotkey

For my poor english and poor chinese language it's hard to communicate
but if you guys can help me, it's really great thanks for all of players with korean
Check it slowly and I'm ready to wait for you Thx~

**Comment by pengg999** [comment]
And what umamusumelocalify file do!!

Sorry for many questions my friend T.T

**Comment by ChihyuenWang** [comment]
Dear @pengg999 ,
Thanks. Your ideas about keep playing in Japanese server is the same as that of most Chinese Umamusume players, we can understand it.
"umamusumelocalify" file is what we used to replace image resources in the game. This project has localized the manga (Appear in the loading screen) in the game. The file is wrapped with Unity3D, and it can be unpacked by other tools (AssetStudio) .
As a contributor to the translated text, I apologize for not being able to answer too many of your questions on the technical side. I think you can keep an eye on this issue, and wait for other contributors’ reply.

**Comment by pengg999** [comment]
ahh I see thank you for your attention~
I'll wait for other developer's comment too
