### ISSUE TITLE
目前插件的翻译原理无法解决一词多义的问题

### ISSUE THREAD

**Issue by MinamiChiwa** [MinamiChiwa/Trainers-Legend-G#6]
目前插件替换相同hash文本的翻译方法无法解决相同文本在不同语境下意义不同的问题。

**举例来讲：** 
` "10221557808549384076": "はい……。",`
这句话会在多种语境下出现，例如主线剧情第三章中教官问到「有没有人想跑2400m」的回复，应译为「我想……」。但在某些语境下「はい」只是个表达肯定的回复，翻译为「我想」无法兼用。

要解决此问题可能需要从插件翻译的原理进行修改。但修改之后也有极大可能令之前已经翻译的成果作废。不知是否有大佬能想出解决方法。

**Comment by akemimadoka** [comment]
之前在添加替换选项文本的时候引入了替换原文的方案，相比现有的直接替换要展示的文本方案是允许根据具体内容替换文本的，这样做会需要改变翻译的格式（迁移本身不难处理）
