### ISSUE TITLE
特别周URA育成出道战后程序报错

### ISSUE THREAD

**Issue by LongLiveLiYue** [MinamiChiwa/Trainers-Legend-G#68]
![报错](https://user-images.githubusercontent.com/110003107/180906069-6001fff8-cfc0-49fe-a65e-d2f3a969a550.png)

**Comment by MinamiChiwa** [comment]
0.88.6还有这个问题吗

**Comment by ChihyuenWang** [comment]
已在[v0.88.6](https://github.com/MinamiChiwa/Trainers-Legend-G/releases/tag/v0.88.6)、[v0.89.0](https://github.com/MinamiChiwa/Trainers-Legend-G/releases/tag/v0.89.0)等多个发行版中尝试修复特别周育成崩溃问题。
若仍复现，请重新发送issue。
