### ISSUE TITLE
受高帧率影响，GrandLive剧本概率性出现「错误 返回标题」问题

### ISSUE THREAD

**Issue by ChihyuenWang** [MinamiChiwa/Trainers-Legend-G#75]
如附图，插件最新发行版中，当游玩GrandLive剧本至URA总决赛结束时，概率性出现弹出「错误 返回标题」的问题。
在外部插件中将游戏帧率设置为90及以下值或开启垂直同步后，难以复现；设置为90以上值时，概率性复现；设置为144时，100%复现。
出现该问题时，游戏返回的Msgpack中并不会出现任何报错。暂时无法定位故障点。
![Picture](https://user-images.githubusercontent.com/12523783/188324043-6d0cf654-367c-4fbd-a040-eb3ecefe8b00.png)

**Comment by ChihyuenWang** [comment]
一些控制变量测试：
①除高帧率（144FPS）以外，关闭插件其他所有功能（译文，字体更换等），不复现此问题。
![Picture1](https://user-images.githubusercontent.com/12523783/188550900-0b766b79-21b1-4d8d-b676-5b4f4771cc97.png)
②保持144FPS，将static.json替换为v0.88.8版本（即没有任何新剧本相关字段），能够复现此问题。
![Picture2](https://user-images.githubusercontent.com/12523783/188550909-3952c7cc-2ad2-4634-85bb-46cc03c5ce6c.png)

这下还真看不出来问题出在哪了（恼

**Comment by MiddleRed** [comment]
补充：不仅是最后URA总决赛结束后会概率报错，只要是因为任何原因育成要结束前（如目标未达成），开着插件的情况下就**有可能报错**，原因未知。   
未确定是否是因为读取数据包导致的，请求控制变量测试。

**Comment by ChihyuenWang** [comment]
根据 @MiddleRed 的提议，我再次进行了一轮控制变量测试。

### 第一组
①maxFPS=144，开启“读取客户端发送包信息”。GrandLive。育成目标未达成结束，未弹出错误。
![Picture1](https://user-images.githubusercontent.com/12523783/188899417-bac5e99e-c460-4027-96de-bab2f9650d20.png)
②maxFPS=144，关闭“读取客户端发送包信息”。GrandLive。育成目标未达成结束，也未弹出错误。
![Picture2](https://user-images.githubusercontent.com/12523783/188900965-39b07f13-b3dd-4616-b2a6-c6e8a574ff8c.png)
### 第二组
①maxFPS=144，开启“读取客户端发送包信息”。GrandLive。URA总决赛完成后结束，弹出了错误。
![Picture3](https://user-images.githubusercontent.com/12523783/188909948-e8ec60c2-16e7-467a-8d51-98a50040b672.png)
②maxFPS=-1（即“游戏原版”），开启“读取客户端发送包信息”。GrandLive。URA总决赛完成后结束，未弹出错误。
![Picture4](https://user-images.githubusercontent.com/12523783/188919506-5ef61b9b-81d9-4f43-b83a-a76c3227ab7e.png)

本轮测试得出的结果是：
①未能复现“因任何原因导致的育成结束（如目标未达成）都有可能报错”， **依然只有在URA总决赛完成后结束才会出现错误。** （也不排除是前者出现的概率太低，两次测试不足以复现。）
②未能证实“读取数据包”与发生错误之间存在联系。 **本轮测试中直接影响错误出现的因素似乎还是只有高帧率。**
然而，在本issue上方的测试中，保留高帧率但关闭插件其他所有功能，也不会产生错误。因此， **仍不能完全认定高帧率是导致该错误发生的唯一因素。**

**Comment by MiddleRed** [comment]
补充：在开启无限制帧数和读取通信包后，同样的错误在URA模式也出现。怀疑青春杯也会有类似问题。

**Comment by ChihyuenWang** [comment]
2022年12月25日，经数次测试，目前不会再出现高帧率下游玩 Grand Live 剧本时育成结束出现「错误 返回标题」的问题。
