### ISSUE TITLE
角色、服装ID整理 / Character ID & Clothes ID

### ISSUE THREAD

**Issue by chinosk114514** [MinamiChiwa/Trainers-Legend-G#79]
- 通用服装

| ID   | 描述                                      |
| ---- | ----------------------------------------- |
| 1    | 通用比赛服                                |
| 2    | 短袖校服                                  |
| 3    | 短裤运动服                                |
| 4    | 通用泳装                                  |
| 5    | 长袖校服                                  |
| 6    | 长裤运动服                                |
| 7    | 通用Live服                                |
| 8    | NPC马娘决胜服（给玩家正常马娘使用无材质） |
| 9    | 温泉浴巾                                  |
| 11   | NPC马娘决胜服2 （没有材质）               |
| 12   | NPC马娘决胜服3（没有材质）                |
| 15   | 没有材质的女性服装                        |
| 25   | 1.5周年 Live 服                           |
| 101  | 马娘通用二星服装                          |
| 102  | 0.5周年Live 服（裤子版）                  |
| 103  | 0.5周年Live 服（裙子版）                  |
| 104  | 1周年 Live 服（短衣尾版）                 |
| 105  | 1周年 Live 服（长衣尾版）                 |

 - 角色ID和专用服装ID已经整理过了, [点击查看](https://github.com/MinamiChiwa/Trainers-Legend-G-TRANS/blob/master/translation-progress.md#角色及皮肤名)
**注意: 专用服装ID和角色ID必须对应, 否则游戏会崩溃**

**Comment by Seiunsky33** [comment]
请问2周年更新后的通用服装ID在哪里可以看到？是否可以考虑在今后的版本更改dressID的格式和文件名匹配？比如泳装特别周1001_30对应id100130，这个没问题，但特别周的原皮是1001_00，但在设置中要打100101才能正确修改。

**Comment by mlbv** [comment]
请问2.5周年的live服id是什么？
