### ISSUE TITLE
2022年10月14日，插件更新后出现UI收窄问题和汉化失效问题

### ISSUE THREAD

**Issue by qweer1238** [MinamiChiwa/Trainers-Legend-G#82]
游戏经过重装检验，确定为BUG。屏幕为分辨率3120*2080.同时建议增加恢复默认功能。
![Uploading 2.png…]()

**Comment by chinosk114514** [comment]
因为更新之后大部分功能都失效了, 不知道cy在搞啥飞机

**Comment by qweer1238** [comment]
> 因为更新之后大部分功能都失效了, 不知道cy在搞啥飞机

逆天CY

**Comment by GEEKiDoS** [comment]
日本人也给我发邮件了, 他发我的日志看起来没啥问题, 可能你得换个方法hook

**Comment by chinosk114514** [comment]
> 日本人也给我发邮件了, 他发我的日志看起来没啥问题, 可能得换个方法hook
> 
> 听说应该是 HyperTech CrackProof 升级了

这就涉及到我的知识盲区了(
请问大佬有啥解决方案吗
![image](https://user-images.githubusercontent.com/74499927/195821634-c3b26443-c700-4e8a-ad84-983333485932.png)

**Comment by akemimadoka** [comment]
发现原因是新版本中有很多方法被内联了，所以原本的 hook 就失效了，暂时不清楚是因为 cy 修改了构建配置还是故意变更的

**Comment by chinosk114514** [comment]
感谢 @akemimadoka , 解锁帧, 汉化和ui的这几项主要功能已修复。
不过仍有部分功能未修复 (如角色替换、自由镜头等)。这些问题我会尽量解决 ~~, 但不保证一定能修好(~~

**Comment by qweer1238** [comment]
> 感谢 @akemimadoka , 解锁帧, 汉化和ui的这几项主要功能已修复。 不过仍有部分功能未修复 (如角色替换、自由镜头等)。这些问题我会尽量解决 ~, 但不保证一定能修好(~

感谢大佬，辛苦了

**Comment by 3271004914** [comment]
请问目前修过的插件怎么下载呢 感觉没有高帧率不会玩游戏了
![image](https://user-images.githubusercontent.com/87769282/196020667-5df18b5b-5ebb-413f-9fda-5afc467da147.png)

**Comment by chinosk114514** [comment]
> 请问目前修过的插件怎么下载呢 感觉没有高帧率不会玩游戏了 ![image](https://user-images.githubusercontent.com/87769282/196020667-5df18b5b-5ebb-413f-9fda-5afc467da147.png)

进入 `Actions` 页面, 选择一个合适的版本, 点进去后找到 `Summary` - `Artifacts` 即可下载
**开发版本不保证没有BUG**

**Comment by ChihyuenWang** [comment]
最新发行版 [v0.89.5](https://github.com/MinamiChiwa/Trainers-Legend-G/releases/tag/v0.89.5)  恢复了汉化、帧数解锁等基础功能的正常运作。感谢报告。

**Comment by qweer1238** [comment]
> 最新发行版 [v0.89.5](https://github.com/MinamiChiwa/Trainers-Legend-G/releases/tag/v0.89.5) 恢复了汉化、帧数解锁等基础功能的正常运作。感谢报告。

赞美大佬
