### ISSUE TITLE
10.19游戏内更新后进入任务界面卡死问题

### ISSUE THREAD

**Issue by LingYuWings** [MinamiChiwa/Trainers-Legend-G#86]
进入任务界面后会白屏卡死，在我这边是每次进入都会触发，不确定是插件导致还是本身的bug

![QQ截图20221019121006](https://user-images.githubusercontent.com/32763318/196595865-85ed5445-5400-4e71-8191-d024e1abc8bb.png)

**Comment by LingYuWings** [comment]
未出现crash，但是log里面报了ArgumentException

[Player.log](https://github.com/MinamiChiwa/Trainers-Legend-G/files/9816782/Player.log)

**Comment by ChihyuenWang** [comment]
出现此问题的原因是译文文件编辑失误，一行任务字段出现了语法错误。
下一版发行版将会修正。
目前可以打开text_data.json，找到：
`"1001335": "【菊花赏】育成时在\\菊花赏取胜",`
将 \\ 改为 \\n ，保存，即可解决问题。

**Comment by ChihyuenWang** [comment]
最新发行版 [v0.89.5](https://github.com/MinamiChiwa/Trainers-Legend-G/releases/tag/v0.89.5)  已修正此问题。感谢报告。
