### ISSUE TITLE
...指令引用了...内存。该内存不能为read

### ISSUE THREAD

**Issue by LinJunhong2** [MinamiChiwa/Trainers-Legend-G#94]
你好，在使用你们的插件时，遇到了一个问题，提示：...指令引用了...内存。该内存不能为read，导致赛马娘不能正常打开。log如下：
[Player.log](https://github.com/MinamiChiwa/Trainers-Legend-G/files/10097840/Player.log)

通过百度，我使用了一些修复方法，也安装过微软的运行库，还是不能正常运行。
麻烦大佬帮忙看看

**Comment by chinosk114514** [comment]
插件版本是？

**Comment by LinJunhong2** [comment]
最新的版本 0.89.11

**Comment by MinamiChiwa** [comment]
![image](https://user-images.githubusercontent.com/78292121/204128819-b09dcfda-60ef-4f6f-afaf-4fc4d7635117.png)
![image](https://user-images.githubusercontent.com/78292121/204128865-16688331-4836-490b-b6f8-245da0792b0e.png)
麻烦检查一下从这里打开的目录，里面的插件版本是不是最新的

**Comment by LinJunhong2** [comment]
![微信截图_20221127175005](https://user-images.githubusercontent.com/32426996/204129014-46846700-10ed-4645-9fb6-aa9a0708946c.png)

版本确认过是最新的
不知道是不是因为我的硬件问题。我的内存是两条不一样牌子的8g

**Comment by MinamiChiwa** [comment]
看你这目录里的legend_g_plugin貌似都没有启动过

**Comment by LinJunhong2** [comment]
截图前我怀疑是没替换好，所以我又把插件的所有文件都替换进去了，然后再打开赛马娘，还是提示相同的错误::>_<::

**Comment by MinamiChiwa** [comment]
上面的目录确定是赛马娘游戏启动的目录吗，这里有很多人装了两个游戏

**Comment by akemimadoka** [comment]
如果完全无法启动的话，有可能是因为运行库版本或者对应操作系统的位数不一致（例如装错旧版运行库或者64位系统安装32位的运行库）

**Comment by chinosk114514** [comment]
试试装运行库吧
https://github.com/abbodi1406/vcredist/releases

**Comment by ChihyuenWang** [comment]
阁下超过 14 天未进行新反馈。视作此 issue 已解决。若仍有问题，请再行反映。感谢支持。

**Comment by Sinxez** [comment]
不好意思，打扰了，今天晚上遇到了同样的问题，其他功能没问题，只有育成打不开，显示了楼主一样的弹窗，是育成过程中突然遇到的。尝试更新了显卡驱动，运行库，仍然没有解决问题，版本是0.91.1
![QQ截图20230228215148](https://user-images.githubusercontent.com/126583671/221873995-7644ead0-bf54-46db-9840-96efc4167859.png)

**Comment by chinosk6** [comment]
> 不好意思，打扰了，今天晚上遇到了同样的问题，其他功能没问题，只有育成打不开，显示了楼主一样的弹窗，是育成过程中突然遇到的。尝试更新了显卡驱动，运行库，仍然没有解决问题，版本是0.91.1 ![QQ截图20230228215148](https://user-images.githubusercontent.com/126583671/221873995-7644ead0-bf54-46db-9840-96efc4167859.png)

是哪位角色的育成呢，能具体说一下触发过程吗
