### ISSUE TITLE
当前的插件版本，关于主线故事中铃鹿的最后一话剧情CG，前半段字幕对不上的问题

### ISSUE THREAD

**Issue by SamaelLuck** [MinamiChiwa/Trainers-Legend-G#96]
在铃鹿的最后一话剧情CG中，开头多了“铃鹿”的台词字幕，导致后面全部慢了半拍，字幕都没有对上，希望大佬们能帮忙解决。

**Comment by ChihyuenWang** [comment]
我们已发现[此问题](https://github.com/MinamiChiwa/Trainers-Legend-G-TRANS/pull/163)  ，将于下一个发行版进行修正。

感谢报告。

**Comment by ChihyuenWang** [comment]
最新发行版 [v0.89.15](https://github.com/MinamiChiwa/Trainers-Legend-G/releases/tag/v0.89.15) 已修复此问题。请更新后进入游戏查看。感谢支持！
